### ISSUE TITLE
JaroWinklerSimilarity returns a distance?

### ISSUE THREAD

**Issue by nightscape** [moj-analytical-services/splink_scalaudfs#3]
Hi all,

[from the code](https://github.com/moj-analytical-services/splink_scalaudfs/blob/74fb8ac1f7e39a486e57d9b38052b0f918f7b769/src/main/scala/uk/gov/moj/dash/linkage/Similarity.scala#L193-L199) it seems as if the `JaroWinklerSimilarity` returns the value of `org.apache.commons.text.similarity.JaroWinklerDistance#distance` without applying a `1 - `  to it.
Is this expected?

```scala
class JaroWinklerSimilarity extends UDF2[String, String, Double] {
  override def call(left: String, right: String): Double = {
    // This has to be instantiated here (i.e. on the worker node)

    if ((left != null) & (right != null)) {
      val distance = new similarity.JaroWinklerDistance()
      distance(left, right)
    } else {
      0.0
    }
  }
}
```

**Comment by mamonu** [comment]
closed as fixed with [release 0.1.0](https://github.com/moj-analytical-services/splink_scalaudfs/releases/tag/v.0.1.0)
